### PR TITLE
Update jq string, change datatypes, strip quotes after colon, also provides a dashboard json 

### PR DESCRIPTION
**Pull request by DerfOh**
Basically this PR makes the rest of the data provided by the API available for queries. Also makes curl be quiet.

### CODE REVIEW

**Comment by gmmoreira** [comment]
Hi @DerfOh. I thank you for the PR. As a suggestion, could you please update the README, adding `sed` as a requirement. You could also describe that an example grafana dashboard is available.

**Comment by DerfOh** [comment]
Rebased, sed explains are commented inline, hopefully this clears some confusion up and allows for command changes to be tracked.

**Comment by gmmoreira** [comment]
Sorry for the delay. I have just accepted your PR. Thank your for the support!

**Comment by DerfOh** [comment]
No problem thanks for getting things started. 

Been playing with the idea of pulling the metrics from telnet api instead of rest as you get much much more info, but I'll keep you posted if I make any progress on that front.

**Pull request merged**
